@include('blog-admin::forms.input', ['name' => 'title', 'controlAttributes' => ['required']])
@include('blog-admin::forms.input', ['name' => 'slug'])
@include('blog-admin::forms.input', ['name' => 'publish_after', 'type' => 'datetime-local'])
@include('blog-admin::forms.input', ['name' => 'author_name'])
@include('blog-admin::forms.textarea', ['name' => 'content', 'controlAttributes' => ['required']])
